import { Country } from './types';

// Full list of countries for comprehensive gameplay
export const COUNTRIES: Country[] = [
  // --- AFRICA (54) ---
  { id: "012", name: "Algeria", code: "dz", capital: "Algiers", continent: "Africa" },
  { id: "024", name: "Angola", code: "ao", capital: "Luanda", continent: "Africa" },
  { id: "204", name: "Benin", code: "bj", capital: "Porto-Novo", continent: "Africa" },
  { id: "072", name: "Botswana", code: "bw", capital: "Gaborone", continent: "Africa" },
  { id: "854", name: "Burkina Faso", code: "bf", capital: "Ouagadougou", continent: "Africa" },
  { id: "108", name: "Burundi", code: "bi", capital: "Gitega", continent: "Africa" },
  { id: "132", name: "Cabo Verde", code: "cv", capital: "Praia", continent: "Africa" },
  { id: "120", name: "Cameroon", code: "cm", capital: "Yaoundé", continent: "Africa" },
  { id: "140", name: "Central African Republic", code: "cf", capital: "Bangui", continent: "Africa" },
  { id: "148", name: "Chad", code: "td", capital: "N'Djamena", continent: "Africa" },
  { id: "174", name: "Comoros", code: "km", capital: "Moroni", continent: "Africa" },
  { id: "180", name: "DR Congo", code: "cd", capital: "Kinshasa", continent: "Africa" },
  { id: "178", name: "Republic of the Congo", code: "cg", capital: "Brazzaville", continent: "Africa" },
  { id: "384", name: "Côte d'Ivoire", code: "ci", capital: "Yamoussoukro", continent: "Africa" },
  { id: "262", name: "Djibouti", code: "dj", capital: "Djibouti", continent: "Africa" },
  { id: "818", name: "Egypt", code: "eg", capital: "Cairo", continent: "Africa" },
  { id: "226", name: "Equatorial Guinea", code: "gq", capital: "Malabo", continent: "Africa" },
  { id: "232", name: "Eritrea", code: "er", capital: "Asmara", continent: "Africa" },
  { id: "748", name: "Eswatini", code: "sz", capital: "Mbabane", continent: "Africa" },
  { id: "231", name: "Ethiopia", code: "et", capital: "Addis Ababa", continent: "Africa" },
  { id: "266", name: "Gabon", code: "ga", capital: "Libreville", continent: "Africa" },
  { id: "270", name: "Gambia", code: "gm", capital: "Banjul", continent: "Africa" },
  { id: "288", name: "Ghana", code: "gh", capital: "Accra", continent: "Africa" },
  { id: "324", name: "Guinea", code: "gn", capital: "Conakry", continent: "Africa" },
  { id: "624", name: "Guinea-Bissau", code: "gw", capital: "Bissau", continent: "Africa" },
  { id: "404", name: "Kenya", code: "ke", capital: "Nairobi", continent: "Africa" },
  { id: "426", name: "Lesotho", code: "ls", capital: "Maseru", continent: "Africa" },
  { id: "430", name: "Liberia", code: "lr", capital: "Monrovia", continent: "Africa" },
  { id: "434", name: "Libya", code: "ly", capital: "Tripoli", continent: "Africa" },
  { id: "450", name: "Madagascar", code: "mg", capital: "Antananarivo", continent: "Africa" },
  { id: "454", name: "Malawi", code: "mw", capital: "Lilongwe", continent: "Africa" },
  { id: "466", name: "Mali", code: "ml", capital: "Bamako", continent: "Africa" },
  { id: "478", name: "Mauritania", code: "mr", capital: "Nouakchott", continent: "Africa" },
  { id: "480", name: "Mauritius", code: "mu", capital: "Port Louis", continent: "Africa" },
  { id: "504", name: "Morocco", code: "ma", capital: "Rabat", continent: "Africa" },
  { id: "508", name: "Mozambique", code: "mz", capital: "Maputo", continent: "Africa" },
  { id: "516", name: "Namibia", code: "na", capital: "Windhoek", continent: "Africa" },
  { id: "562", name: "Niger", code: "ne", capital: "Niamey", continent: "Africa" },
  { id: "566", name: "Nigeria", code: "ng", capital: "Abuja", continent: "Africa" },
  { id: "646", name: "Rwanda", code: "rw", capital: "Kigali", continent: "Africa" },
  { id: "678", name: "Sao Tome and Principe", code: "st", capital: "São Tomé", continent: "Africa" },
  { id: "686", name: "Senegal", code: "sn", capital: "Dakar", continent: "Africa" },
  { id: "690", name: "Seychelles", code: "sc", capital: "Victoria", continent: "Africa" },
  { id: "694", name: "Sierra Leone", code: "sl", capital: "Freetown", continent: "Africa" },
  { id: "706", name: "Somalia", code: "so", capital: "Mogadishu", continent: "Africa" },
  { id: "710", name: "South Africa", code: "za", capital: "Pretoria", continent: "Africa" },
  { id: "728", name: "South Sudan", code: "ss", capital: "Juba", continent: "Africa" },
  { id: "729", name: "Sudan", code: "sd", capital: "Khartoum", continent: "Africa" },
  { id: "834", name: "Tanzania", code: "tz", capital: "Dodoma", continent: "Africa" },
  { id: "768", name: "Togo", code: "tg", capital: "Lomé", continent: "Africa" },
  { id: "788", name: "Tunisia", code: "tn", capital: "Tunis", continent: "Africa" },
  { id: "800", name: "Uganda", code: "ug", capital: "Kampala", continent: "Africa" },
  { id: "894", name: "Zambia", code: "zm", capital: "Lusaka", continent: "Africa" },
  { id: "716", name: "Zimbabwe", code: "zw", capital: "Harare", continent: "Africa" },

  // --- ASIA (49) ---
  { id: "004", name: "Afghanistan", code: "af", capital: "Kabul", continent: "Asia" },
  { id: "051", name: "Armenia", code: "am", capital: "Yerevan", continent: "Asia" },
  { id: "031", name: "Azerbaijan", code: "az", capital: "Baku", continent: "Asia" },
  { id: "048", name: "Bahrain", code: "bh", capital: "Manama", continent: "Asia" },
  { id: "050", name: "Bangladesh", code: "bd", capital: "Dhaka", continent: "Asia" },
  { id: "064", name: "Bhutan", code: "bt", capital: "Thimphu", continent: "Asia" },
  { id: "096", name: "Brunei", code: "bn", capital: "Bandar Seri Begawan", continent: "Asia" },
  { id: "116", name: "Cambodia", code: "kh", capital: "Phnom Penh", continent: "Asia" },
  { id: "156", name: "China", code: "cn", capital: "Beijing", continent: "Asia" },
  { id: "196", name: "Cyprus", code: "cy", capital: "Nicosia", continent: "Asia" },
  { id: "268", name: "Georgia", code: "ge", capital: "Tbilisi", continent: "Asia" },
  { id: "356", name: "India", code: "in", capital: "New Delhi", continent: "Asia" },
  { id: "360", name: "Indonesia", code: "id", capital: "Jakarta", continent: "Asia" },
  { id: "364", name: "Iran", code: "ir", capital: "Tehran", continent: "Asia" },
  { id: "368", name: "Iraq", code: "iq", capital: "Baghdad", continent: "Asia" },
  { id: "376", name: "Israel", code: "il", capital: "Jerusalem", continent: "Asia" },
  { id: "392", name: "Japan", code: "jp", capital: "Tokyo", continent: "Asia" },
  { id: "400", name: "Jordan", code: "jo", capital: "Amman", continent: "Asia" },
  { id: "398", name: "Kazakhstan", code: "kz", capital: "Astana", continent: "Asia" },
  { id: "414", name: "Kuwait", code: "kw", capital: "Kuwait City", continent: "Asia" },
  { id: "417", name: "Kyrgyzstan", code: "kg", capital: "Bishkek", continent: "Asia" },
  { id: "418", name: "Laos", code: "la", capital: "Vientiane", continent: "Asia" },
  { id: "422", name: "Lebanon", code: "lb", capital: "Beirut", continent: "Asia" },
  { id: "458", name: "Malaysia", code: "my", capital: "Kuala Lumpur", continent: "Asia" },
  { id: "462", name: "Maldives", code: "mv", capital: "Malé", continent: "Asia" },
  { id: "496", name: "Mongolia", code: "mn", capital: "Ulaanbaatar", continent: "Asia" },
  { id: "104", name: "Myanmar", code: "mm", capital: "Naypyidaw", continent: "Asia" },
  { id: "524", name: "Nepal", code: "np", capital: "Kathmandu", continent: "Asia" },
  { id: "408", name: "North Korea", code: "kp", capital: "Pyongyang", continent: "Asia" },
  { id: "512", name: "Oman", code: "om", capital: "Muscat", continent: "Asia" },
  { id: "586", name: "Pakistan", code: "pk", capital: "Islamabad", continent: "Asia" },
  { id: "608", name: "Philippines", code: "ph", capital: "Manila", continent: "Asia" },
  { id: "634", name: "Qatar", code: "qa", capital: "Doha", continent: "Asia" },
  { id: "682", name: "Saudi Arabia", code: "sa", capital: "Riyadh", continent: "Asia" },
  { id: "702", name: "Singapore", code: "sg", capital: "Singapore", continent: "Asia" },
  { id: "410", name: "South Korea", code: "kr", capital: "Seoul", continent: "Asia" },
  { id: "144", name: "Sri Lanka", code: "lk", capital: "Colombo", continent: "Asia" },
  { id: "760", name: "Syria", code: "sy", capital: "Damascus", continent: "Asia" },
  { id: "158", name: "Taiwan", code: "tw", capital: "Taipei", continent: "Asia" },
  { id: "762", name: "Tajikistan", code: "tj", capital: "Dushanbe", continent: "Asia" },
  { id: "764", name: "Thailand", code: "th", capital: "Bangkok", continent: "Asia" },
  { id: "626", name: "Timor-Leste", code: "tl", capital: "Dili", continent: "Asia" },
  { id: "792", name: "Turkey", code: "tr", capital: "Ankara", continent: "Asia" },
  { id: "795", name: "Turkmenistan", code: "tm", capital: "Ashgabat", continent: "Asia" },
  { id: "784", name: "United Arab Emirates", code: "ae", capital: "Abu Dhabi", continent: "Asia" },
  { id: "860", name: "Uzbekistan", code: "uz", capital: "Tashkent", continent: "Asia" },
  { id: "704", name: "Vietnam", code: "vn", capital: "Hanoi", continent: "Asia" },
  { id: "887", name: "Yemen", code: "ye", capital: "Sana'a", continent: "Asia" },

  // --- EUROPE (45) ---
  { id: "008", name: "Albania", code: "al", capital: "Tirana", continent: "Europe" },
  { id: "020", name: "Andorra", code: "ad", capital: "Andorra la Vella", continent: "Europe" },
  { id: "040", name: "Austria", code: "at", capital: "Vienna", continent: "Europe" },
  { id: "112", name: "Belarus", code: "by", capital: "Minsk", continent: "Europe" },
  { id: "056", name: "Belgium", code: "be", capital: "Brussels", continent: "Europe" },
  { id: "070", name: "Bosnia and Herzegovina", code: "ba", capital: "Sarajevo", continent: "Europe" },
  { id: "100", name: "Bulgaria", code: "bg", capital: "Sofia", continent: "Europe" },
  { id: "191", name: "Croatia", code: "hr", capital: "Zagreb", continent: "Europe" },
  { id: "203", name: "Czech Republic", code: "cz", capital: "Prague", continent: "Europe" },
  { id: "208", name: "Denmark", code: "dk", capital: "Copenhagen", continent: "Europe" },
  { id: "233", name: "Estonia", code: "ee", capital: "Tallinn", continent: "Europe" },
  { id: "246", name: "Finland", code: "fi", capital: "Helsinki", continent: "Europe" },
  { id: "250", name: "France", code: "fr", capital: "Paris", continent: "Europe" },
  { id: "276", name: "Germany", code: "de", capital: "Berlin", continent: "Europe" },
  { id: "300", name: "Greece", code: "gr", capital: "Athens", continent: "Europe" },
  { id: "348", name: "Hungary", code: "hu", capital: "Budapest", continent: "Europe" },
  { id: "352", name: "Iceland", code: "is", capital: "Reykjavik", continent: "Europe" },
  { id: "372", name: "Ireland", code: "ie", capital: "Dublin", continent: "Europe" },
  { id: "380", name: "Italy", code: "it", capital: "Rome", continent: "Europe" },
  { id: "383", name: "Kosovo", code: "xk", capital: "Pristina", continent: "Europe" },
  { id: "428", name: "Latvia", code: "lv", capital: "Riga", continent: "Europe" },
  { id: "438", name: "Liechtenstein", code: "li", capital: "Vaduz", continent: "Europe" },
  { id: "440", name: "Lithuania", code: "lt", capital: "Vilnius", continent: "Europe" },
  { id: "442", name: "Luxembourg", code: "lu", capital: "Luxembourg", continent: "Europe" },
  { id: "470", name: "Malta", code: "mt", capital: "Valletta", continent: "Europe" },
  { id: "498", name: "Moldova", code: "md", capital: "Chisinau", continent: "Europe" },
  { id: "492", name: "Monaco", code: "mc", capital: "Monaco", continent: "Europe" },
  { id: "499", name: "Montenegro", code: "me", capital: "Podgorica", continent: "Europe" },
  { id: "528", name: "Netherlands", code: "nl", capital: "Amsterdam", continent: "Europe" },
  { id: "807", name: "North Macedonia", code: "mk", capital: "Skopje", continent: "Europe" },
  { id: "578", name: "Norway", code: "no", capital: "Oslo", continent: "Europe" },
  { id: "616", name: "Poland", code: "pl", capital: "Warsaw", continent: "Europe" },
  { id: "620", name: "Portugal", code: "pt", capital: "Lisbon", continent: "Europe" },
  { id: "642", name: "Romania", code: "ro", capital: "Bucharest", continent: "Europe" },
  { id: "643", name: "Russia", code: "ru", capital: "Moscow", continent: "Europe" },
  { id: "674", name: "San Marino", code: "sm", capital: "San Marino", continent: "Europe" },
  { id: "688", name: "Serbia", code: "rs", capital: "Belgrade", continent: "Europe" },
  { id: "703", name: "Slovakia", code: "sk", capital: "Bratislava", continent: "Europe" },
  { id: "705", name: "Slovenia", code: "si", capital: "Ljubljana", continent: "Europe" },
  { id: "724", name: "Spain", code: "es", capital: "Madrid", continent: "Europe" },
  { id: "752", name: "Sweden", code: "se", capital: "Stockholm", continent: "Europe" },
  { id: "756", name: "Switzerland", code: "ch", capital: "Bern", continent: "Europe" },
  { id: "804", name: "Ukraine", code: "ua", capital: "Kyiv", continent: "Europe" },
  { id: "826", name: "United Kingdom", code: "gb", capital: "London", continent: "Europe" },
  { id: "336", name: "Vatican City", code: "va", capital: "Vatican City", continent: "Europe" },

  // --- NORTH AMERICA (23) ---
  { id: "028", name: "Antigua and Barbuda", code: "ag", capital: "Saint John's", continent: "North America" },
  { id: "044", name: "Bahamas", code: "bs", capital: "Nassau", continent: "North America" },
  { id: "052", name: "Barbados", code: "bb", capital: "Bridgetown", continent: "North America" },
  { id: "084", name: "Belize", code: "bz", capital: "Belmopan", continent: "North America" },
  { id: "124", name: "Canada", code: "ca", capital: "Ottawa", continent: "North America" },
  { id: "188", name: "Costa Rica", code: "cr", capital: "San José", continent: "North America" },
  { id: "192", name: "Cuba", code: "cu", capital: "Havana", continent: "North America" },
  { id: "212", name: "Dominica", code: "dm", capital: "Roseau", continent: "North America" },
  { id: "214", name: "Dominican Republic", code: "do", capital: "Santo Domingo", continent: "North America" },
  { id: "222", name: "El Salvador", code: "sv", capital: "San Salvador", continent: "North America" },
  { id: "308", name: "Grenada", code: "gd", capital: "Saint George's", continent: "North America" },
  { id: "320", name: "Guatemala", code: "gt", capital: "Guatemala City", continent: "North America" },
  { id: "332", name: "Haiti", code: "ht", capital: "Port-au-Prince", continent: "North America" },
  { id: "340", name: "Honduras", code: "hn", capital: "Tegucigalpa", continent: "North America" },
  { id: "388", name: "Jamaica", code: "jm", capital: "Kingston", continent: "North America" },
  { id: "484", name: "Mexico", code: "mx", capital: "Mexico City", continent: "North America" },
  { id: "558", name: "Nicaragua", code: "ni", capital: "Managua", continent: "North America" },
  { id: "591", name: "Panama", code: "pa", capital: "Panama City", continent: "North America" },
  { id: "659", name: "Saint Kitts and Nevis", code: "kn", capital: "Basseterre", continent: "North America" },
  { id: "662", name: "Saint Lucia", code: "lc", capital: "Castries", continent: "North America" },
  { id: "670", name: "Saint Vincent and the Grenadines", code: "vc", capital: "Kingstown", continent: "North America" },
  { id: "780", name: "Trinidad and Tobago", code: "tt", capital: "Port of Spain", continent: "North America" },
  { id: "840", name: "United States", code: "us", capital: "Washington, D.C.", continent: "North America" },

  // --- OCEANIA (14) ---
  { id: "036", name: "Australia", code: "au", capital: "Canberra", continent: "Oceania" },
  { id: "242", name: "Fiji", code: "fj", capital: "Suva", continent: "Oceania" },
  { id: "296", name: "Kiribati", code: "ki", capital: "South Tarawa", continent: "Oceania" },
  { id: "584", name: "Marshall Islands", code: "mh", capital: "Majuro", continent: "Oceania" },
  { id: "583", name: "Micronesia", code: "fm", capital: "Palikir", continent: "Oceania" },
  { id: "520", name: "Nauru", code: "nr", capital: "Yaren", continent: "Oceania" },
  { id: "554", name: "New Zealand", code: "nz", capital: "Wellington", continent: "Oceania" },
  { id: "585", name: "Palau", code: "pw", capital: "Ngerulmud", continent: "Oceania" },
  { id: "598", name: "Papua New Guinea", code: "pg", capital: "Port Moresby", continent: "Oceania" },
  { id: "882", name: "Samoa", code: "ws", capital: "Apia", continent: "Oceania" },
  { id: "090", name: "Solomon Islands", code: "sb", capital: "Honiara", continent: "Oceania" },
  { id: "776", name: "Tonga", code: "to", capital: "Nukuʻalofa", continent: "Oceania" },
  { id: "798", name: "Tuvalu", code: "tv", capital: "Funafuti", continent: "Oceania" },
  { id: "548", name: "Vanuatu", code: "vu", capital: "Port Vila", continent: "Oceania" },

  // --- SOUTH AMERICA (12) ---
  { id: "032", name: "Argentina", code: "ar", capital: "Buenos Aires", continent: "South America" },
  { id: "068", name: "Bolivia", code: "bo", capital: "Sucre", continent: "South America" },
  { id: "076", name: "Brazil", code: "br", capital: "Brasilia", continent: "South America" },
  { id: "152", name: "Chile", code: "cl", capital: "Santiago", continent: "South America" },
  { id: "170", name: "Colombia", code: "co", capital: "Bogota", continent: "South America" },
  { id: "218", name: "Ecuador", code: "ec", capital: "Quito", continent: "South America" },
  { id: "328", name: "Guyana", code: "gy", capital: "Georgetown", continent: "South America" },
  { id: "600", name: "Paraguay", code: "py", capital: "Asunción", continent: "South America" },
  { id: "604", name: "Peru", code: "pe", capital: "Lima", continent: "South America" },
  { id: "740", name: "Suriname", code: "sr", capital: "Paramaribo", continent: "South America" },
  { id: "858", name: "Uruguay", code: "uy", capital: "Montevideo", continent: "South America" },
  { id: "862", name: "Venezuela", code: "ve", capital: "Caracas", continent: "South America" },
];

export const CONTINENTS = ["Africa", "Asia", "Europe", "North America", "Oceania", "South America"];

export const MAX_QUESTIONS = 5; // kept for reference, no longer the game-over condition
export const MAX_MISTAKES = 3;
export const MAX_CLUES = 3;
export const MAX_BONUS_ROUNDS = 2;
export const TIMER_SECONDS = 10;
export const POINTS_COUNTRY = 20;
export const POINTS_BONUS = 5;
export const WORLD_TOPO_URL = "https://cdn.jsdelivr.net/npm/world-atlas@2/countries-50m.json";

export const GREETINGS: Record<string, { language: string; hello: string }> = {
  // Africa
  dz: { language: "Arabic", hello: "مرحبا" },
  ao: { language: "Portuguese", hello: "Olá" },
  bj: { language: "French", hello: "Bonjour" },
  bw: { language: "Setswana", hello: "Dumela" },
  bf: { language: "French", hello: "Bonjour" },
  bi: { language: "Kirundi", hello: "Muraho" },
  cv: { language: "Portuguese", hello: "Olá" },
  cm: { language: "French", hello: "Bonjour" },
  cf: { language: "French", hello: "Bonjour" },
  td: { language: "French", hello: "Bonjour" },
  km: { language: "Comorian", hello: "Salama" },
  cd: { language: "French", hello: "Bonjour" },
  cg: { language: "French", hello: "Bonjour" },
  ci: { language: "French", hello: "Bonjour" },
  dj: { language: "French", hello: "Bonjour" },
  eg: { language: "Arabic", hello: "أهلاً" },
  gq: { language: "Spanish", hello: "Hola" },
  er: { language: "Tigrinya", hello: "ሰላም" },
  sz: { language: "Swazi", hello: "Sawubona" },
  et: { language: "Amharic", hello: "ሰላም" },
  ga: { language: "French", hello: "Bonjour" },
  gm: { language: "English", hello: "Hello" },
  gh: { language: "Twi", hello: "Akwaaba" },
  gn: { language: "French", hello: "Bonjour" },
  gw: { language: "Portuguese", hello: "Olá" },
  ke: { language: "Swahili", hello: "Habari" },
  ls: { language: "Sesotho", hello: "Lumela" },
  lr: { language: "English", hello: "Hello" },
  ly: { language: "Arabic", hello: "مرحبا" },
  mg: { language: "Malagasy", hello: "Salama" },
  mw: { language: "Chichewa", hello: "Moni" },
  ml: { language: "French", hello: "Bonjour" },
  mr: { language: "Arabic", hello: "مرحبا" },
  mu: { language: "French", hello: "Bonjour" },
  ma: { language: "Arabic", hello: "مرحبا" },
  mz: { language: "Portuguese", hello: "Olá" },
  na: { language: "Afrikaans", hello: "Hallo" },
  ne: { language: "French", hello: "Bonjour" },
  ng: { language: "Yoruba", hello: "Bawo ni" },
  rw: { language: "Kinyarwanda", hello: "Muraho" },
  st: { language: "Portuguese", hello: "Olá" },
  sn: { language: "Wolof", hello: "Salaam" },
  sc: { language: "Creole", hello: "Bonzour" },
  sl: { language: "English", hello: "Hello" },
  so: { language: "Somali", hello: "Nabad" },
  za: { language: "Zulu", hello: "Sawubona" },
  ss: { language: "English", hello: "Hello" },
  sd: { language: "Arabic", hello: "مرحبا" },
  tz: { language: "Swahili", hello: "Habari" },
  tg: { language: "French", hello: "Bonjour" },
  tn: { language: "Arabic", hello: "مرحبا" },
  ug: { language: "Luganda", hello: "Oli otya" },
  zm: { language: "English", hello: "Hello" },
  zw: { language: "Shona", hello: "Mhoro" },
  // Asia
  af: { language: "Dari", hello: "سلام" },
  am: { language: "Armenian", hello: "Բարև" },
  az: { language: "Azerbaijani", hello: "Salam" },
  bh: { language: "Arabic", hello: "مرحبا" },
  bd: { language: "Bengali", hello: "নমস্কার" },
  bt: { language: "Dzongkha", hello: "Kuzu Zangpo" },
  bn: { language: "Malay", hello: "Helo" },
  kh: { language: "Khmer", hello: "ជំរាបសួរ" },
  cn: { language: "Mandarin", hello: "你好" },
  cy: { language: "Greek", hello: "Γεια σου" },
  ge: { language: "Georgian", hello: "გამარჯობა" },
  in: { language: "Hindi", hello: "नमस्ते" },
  id: { language: "Indonesian", hello: "Halo" },
  ir: { language: "Persian", hello: "سلام" },
  iq: { language: "Arabic", hello: "مرحبا" },
  il: { language: "Hebrew", hello: "שָׁלוֹם" },
  jp: { language: "Japanese", hello: "こんにちは" },
  jo: { language: "Arabic", hello: "مرحبا" },
  kz: { language: "Kazakh", hello: "Сәлем" },
  kw: { language: "Arabic", hello: "مرحبا" },
  kg: { language: "Kyrgyz", hello: "Салам" },
  la: { language: "Lao", hello: "ສະບາຍດີ" },
  lb: { language: "Arabic", hello: "مرحبا" },
  my: { language: "Malay", hello: "Helo" },
  mv: { language: "Dhivehi", hello: "ހެލޯ" },
  mn: { language: "Mongolian", hello: "Сайн уу" },
  mm: { language: "Burmese", hello: "မင်္ဂလာပါ" },
  np: { language: "Nepali", hello: "नमस्ते" },
  kp: { language: "Korean", hello: "안녕하세요" },
  om: { language: "Arabic", hello: "مرحبا" },
  pk: { language: "Urdu", hello: "ہیلو" },
  ph: { language: "Filipino", hello: "Kamusta" },
  qa: { language: "Arabic", hello: "مرحبا" },
  sa: { language: "Arabic", hello: "مرحبا" },
  sg: { language: "English", hello: "Hello" },
  kr: { language: "Korean", hello: "안녕하세요" },
  lk: { language: "Sinhala", hello: "ආයුබෝවන්" },
  sy: { language: "Arabic", hello: "مرحبا" },
  tw: { language: "Mandarin", hello: "你好" },
  tj: { language: "Tajik", hello: "Салом" },
  th: { language: "Thai", hello: "สวัสดี" },
  tl: { language: "Tetum", hello: "Bondia" },
  tr: { language: "Turkish", hello: "Merhaba" },
  tm: { language: "Turkmen", hello: "Salam" },
  ae: { language: "Arabic", hello: "مرحبا" },
  uz: { language: "Uzbek", hello: "Salom" },
  vn: { language: "Vietnamese", hello: "Xin chào" },
  ye: { language: "Arabic", hello: "مرحبا" },
  // Europe
  al: { language: "Albanian", hello: "Përshëndetje" },
  ad: { language: "Catalan", hello: "Hola" },
  at: { language: "German", hello: "Hallo" },
  by: { language: "Belarusian", hello: "Прывітанне" },
  be: { language: "French", hello: "Bonjour" },
  ba: { language: "Bosnian", hello: "Zdravo" },
  bg: { language: "Bulgarian", hello: "Здравейте" },
  hr: { language: "Croatian", hello: "Zdravo" },
  cz: { language: "Czech", hello: "Ahoj" },
  dk: { language: "Danish", hello: "Hej" },
  ee: { language: "Estonian", hello: "Tere" },
  fi: { language: "Finnish", hello: "Hei" },
  fr: { language: "French", hello: "Bonjour" },
  de: { language: "German", hello: "Hallo" },
  gr: { language: "Greek", hello: "Γεια σου" },
  hu: { language: "Hungarian", hello: "Szia" },
  is: { language: "Icelandic", hello: "Halló" },
  ie: { language: "English", hello: "Hello" },
  it: { language: "Italian", hello: "Ciao" },
  xk: { language: "Albanian", hello: "Përshëndetje" },
  lv: { language: "Latvian", hello: "Sveiki" },
  li: { language: "German", hello: "Hallo" },
  lt: { language: "Lithuanian", hello: "Labas" },
  lu: { language: "Luxembourgish", hello: "Moïen" },
  mt: { language: "Maltese", hello: "Bongu" },
  md: { language: "Romanian", hello: "Bună" },
  mc: { language: "French", hello: "Bonjour" },
  me: { language: "Montenegrin", hello: "Zdravo" },
  nl: { language: "Dutch", hello: "Hallo" },
  mk: { language: "Macedonian", hello: "Здраво" },
  no: { language: "Norwegian", hello: "Hei" },
  pl: { language: "Polish", hello: "Cześć" },
  pt: { language: "Portuguese", hello: "Olá" },
  ro: { language: "Romanian", hello: "Bună" },
  ru: { language: "Russian", hello: "Привет" },
  sm: { language: "Italian", hello: "Ciao" },
  rs: { language: "Serbian", hello: "Zdravo" },
  sk: { language: "Slovak", hello: "Ahoj" },
  si: { language: "Slovenian", hello: "Zdravo" },
  es: { language: "Spanish", hello: "Hola" },
  se: { language: "Swedish", hello: "Hej" },
  ch: { language: "German", hello: "Hallo" },
  ua: { language: "Ukrainian", hello: "Привіт" },
  gb: { language: "English", hello: "Hello" },
  va: { language: "Italian", hello: "Ciao" },
  // North America
  ag: { language: "English", hello: "Hello" },
  bs: { language: "English", hello: "Hello" },
  bb: { language: "English", hello: "Hello" },
  bz: { language: "English", hello: "Hello" },
  ca: { language: "English", hello: "Hello" },
  cr: { language: "Spanish", hello: "Hola" },
  cu: { language: "Spanish", hello: "Hola" },
  dm: { language: "English", hello: "Hello" },
  do: { language: "Spanish", hello: "Hola" },
  sv: { language: "Spanish", hello: "Hola" },
  gd: { language: "English", hello: "Hello" },
  gt: { language: "Spanish", hello: "Hola" },
  ht: { language: "Haitian Creole", hello: "Bonjou" },
  hn: { language: "Spanish", hello: "Hola" },
  jm: { language: "English", hello: "Hello" },
  mx: { language: "Spanish", hello: "Hola" },
  ni: { language: "Spanish", hello: "Hola" },
  pa: { language: "Spanish", hello: "Hola" },
  kn: { language: "English", hello: "Hello" },
  lc: { language: "English", hello: "Hello" },
  vc: { language: "English", hello: "Hello" },
  tt: { language: "English", hello: "Hello" },
  us: { language: "English", hello: "Hello" },
  // Oceania
  au: { language: "English", hello: "Hello" },
  fj: { language: "Fijian", hello: "Bula" },
  ki: { language: "Gilbertese", hello: "Mauri" },
  mh: { language: "Marshallese", hello: "Iakwe" },
  fm: { language: "English", hello: "Hello" },
  nr: { language: "Nauruan", hello: "Ekamawir" },
  nz: { language: "Māori", hello: "Kia ora" },
  pw: { language: "Palauan", hello: "Alii" },
  pg: { language: "Tok Pisin", hello: "Gude" },
  ws: { language: "Samoan", hello: "Talofa" },
  sb: { language: "English", hello: "Hello" },
  to: { language: "Tongan", hello: "Malo" },
  tv: { language: "Tuvaluan", hello: "Talofa" },
  vu: { language: "Bislama", hello: "Halo" },
  // South America
  ar: { language: "Spanish", hello: "Hola" },
  bo: { language: "Spanish", hello: "Hola" },
  br: { language: "Portuguese", hello: "Olá" },
  cl: { language: "Spanish", hello: "Hola" },
  co: { language: "Spanish", hello: "Hola" },
  ec: { language: "Spanish", hello: "Hola" },
  gy: { language: "English", hello: "Hello" },
  py: { language: "Guaraní", hello: "Mba'éichapa" },
  pe: { language: "Spanish", hello: "Hola" },
  sr: { language: "Dutch", hello: "Hallo" },
  uy: { language: "Spanish", hello: "Hola" },
  ve: { language: "Spanish", hello: "Hola" },
};